
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miko ja Nastia
 */
public class cardrescondra extends javax.swing.JDialog {

    /**
     * Creates new form cardrescondra
     */
    public cardrescondra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setValues() {
        String days[] = new String[31];
        days[0] = "" + 0 + 1;
        for (int i = 1; i < days.length; i ++) {
            days[i] = "" + (i + 1);
            if (days[i].length() < 2) {
                days[i] = 0 + days[i];
            }
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(days);
        daybox.setModel(model);
        
        String months[] = new String[12];
        months[0] = "" + 0 + 1;
               for (int i = 1; i < months.length; i ++) {
            months[i] = "" + (i + 1);
            if (months[i].length() < 2) {
                months[i] = 0 + months[i];
            }
            
        }
        DefaultComboBoxModel modelmm = new DefaultComboBoxModel(months);
        
        monthbox.setModel(modelmm);
        
        String years[] = new String[20]; 
        
                       for (int i = 0; i < years.length; i ++) {
            years[i] = "" + (2019 + i);
        }
        DefaultComboBoxModel modelyyyy = new DefaultComboBoxModel(years);
        
        yearbox.setModel(modelyyyy);
        
         DefaultComboBoxModel modelseconddd = new DefaultComboBoxModel(days);
         DefaultComboBoxModel modelmmsecond = new DefaultComboBoxModel(months);
         DefaultComboBoxModel modelyyyysecond = new DefaultComboBoxModel(years);
         
         seconddaybox.setModel(modelseconddd);
         secondmonthbox.setModel(modelmmsecond);
         secondyearbox.setModel(modelyyyysecond);
         
         String[] pannkkivaikateinen = new String[3];
         pannkkivaikateinen[0] = "Kaikki";
         pannkkivaikateinen[1] = "Käteinen";
         pannkkivaikateinen[2] = "Pankkikortti";
         DefaultComboBoxModel kateinenvaipankki = new DefaultComboBoxModel(pannkkivaikateinen);
         cardcash.setModel(kateinenvaipankki);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabletti = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        daybox = new javax.swing.JComboBox<>();
        monthbox = new javax.swing.JComboBox<>();
        yearbox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        seconddaybox = new javax.swing.JComboBox<>();
        secondmonthbox = new javax.swing.JComboBox<>();
        secondyearbox = new javax.swing.JComboBox<>();
        cardcash = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        yhteensa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabletti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabletti);

        jLabel1.setText("Valitse");

        daybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        daybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayboxActionPerformed(evt);
            }
        });

        monthbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        yearbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("-");

        seconddaybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        secondmonthbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        secondyearbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cardcash.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cardcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardcashActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Kaikki myynnit yhteensä:");

        yhteensa.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(daybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(monthbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(yearbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(seconddaybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(secondmonthbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(secondyearbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cardcash, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yhteensa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(daybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(seconddaybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondmonthbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondyearbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardcash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(yhteensa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardcashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardcashActionPerformed

    private void dayboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayboxActionPerformed
      
    }//GEN-LAST:event_dayboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
          AccessToMysql mysql = new AccessToMysql();
          mysql.connectah();
           String col[] = {"Kuitti NRO", "Pöytä NRO","Maksutapa","PVM", "Klo", "Hinta"};     
           DefaultTableModel model = new DefaultTableModel(col, 0);
          String eka = "'" + secondyearbox.getSelectedItem().toString() + "-" + secondmonthbox.getSelectedItem().toString() + "-" + seconddaybox.getSelectedItem().toString() + "'";
          String toka = "'" + yearbox.getSelectedItem().toString() + "-" + monthbox.getSelectedItem().toString() + "-" + daybox.getSelectedItem().toString() + "'";
          
          
          if (cardcash.getSelectedItem().equals("Käteinen")) {
              try {
                  mysql.cardresconrakateinen(model, eka, toka);
              } catch (SQLException ex) {
                  Logger.getLogger(cardrescondra.class.getName()).log(Level.SEVERE, null, ex);
              } catch (ParseException ex) {
                  Logger.getLogger(cardrescondra.class.getName()).log(Level.SEVERE, null, ex);
              }
               tabletti.setModel(model);
               
              try {
                  yhteensa.setText("" + mysql.rescondkateinensumma(eka, toka));
              } catch (SQLException ex) {
                  Logger.getLogger(cardrescondra.class.getName()).log(Level.SEVERE, null, ex);
              }
               
               
          }
                else if (cardcash.getSelectedItem().equals("Kaikki")) {
          try {
              mysql.cardrescondraall(model, eka, toka);
          } catch (SQLException ex) {
              Logger.getLogger(cardrescondra.class.getName()).log(Level.SEVERE, null, ex);
          } catch (ParseException ex) {
            Logger.getLogger(cardrescondra.class.getName()).log(Level.SEVERE, null, ex);
        }
          tabletti.setModel(model);
          
              try {
                  yhteensa.setText("" + mysql.rescondraallsumma(eka, toka));
              } catch (SQLException ex) {
                  Logger.getLogger(cardrescondra.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
          
                else if (cardcash.getSelectedItem().equals("Pankkikortti")) {
              try {
                  mysql.cardresconrapankki(model, eka, toka);
              } catch (SQLException ex) {
                  Logger.getLogger(cardrescondra.class.getName()).log(Level.SEVERE, null, ex);
              } catch (ParseException ex) {
                  Logger.getLogger(cardrescondra.class.getName()).log(Level.SEVERE, null, ex);
              }
              tabletti.setModel(model);
              
              try {
                  yhteensa.setText("" + mysql.rescondkorttisumma(eka, toka));
              } catch (SQLException ex) {
                  Logger.getLogger(cardrescondra.class.getName()).log(Level.SEVERE, null, ex);
              }
                }
          
          
          
          try {
              mysql.closeConnect();
          } catch (SQLException ex) {
              Logger.getLogger(cardrescondra.class.getName()).log(Level.SEVERE, null, ex);
          }
         
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cardrescondra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cardrescondra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cardrescondra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cardrescondra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cardrescondra dialog = new cardrescondra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cardcash;
    private javax.swing.JComboBox<String> daybox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> monthbox;
    private javax.swing.JComboBox<String> seconddaybox;
    private javax.swing.JComboBox<String> secondmonthbox;
    private javax.swing.JComboBox<String> secondyearbox;
    private javax.swing.JTable tabletti;
    private javax.swing.JComboBox<String> yearbox;
    private javax.swing.JLabel yhteensa;
    // End of variables declaration//GEN-END:variables
}
