
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miko ja Nastia
 */
public class CustomersDialog extends javax.swing.JDialog {

  
  String col[] = {"ID", "Etunimi","Sukunimi","S-posti", "Puh numero", "Muistiinpanot", "Lisäys pvm"};     
  DefaultTableModel tablemodel = new DefaultTableModel(col, 0);
    public static SingleCustomer singlecustomer;
    /**
     * Creates new form CustomersDialog
     */
    public CustomersDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setTable() throws SQLException, ParseException {
       AccessToMysql mysql = new AccessToMysql();
       mysql.connectah();
       DefaultTableModel model = (DefaultTableModel) tabletti.getModel();
       model.setRowCount(0);
       tablemodel = mysql.getallcustomers(tablemodel);
       tabletti.setModel(tablemodel);
        this.tabletti.setDefaultEditor(Object.class, null);
        mysql.closeConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabletti = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabletti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabletti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablettiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabletti);

        jButton1.setText("Lisää uusi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hae asiakasta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       singlecustomer = new SingleCustomer(Mainclass.firstpage, true);
       AccessToMysql mysql = new AccessToMysql();
       mysql.connectah();
       int customersidluku = 0;
       
      try {
          customersidluku = mysql.getCustomerscount() + 1;
      } catch (SQLException ex) {
          Logger.getLogger(CustomersDialog.class.getName()).log(Level.SEVERE, null, ex);
      }
    singlecustomer.customerid.setText("" + customersidluku);
      singlecustomer.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablettiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablettiMouseClicked
     
         if (evt.getClickCount() == 2) {
        
           
        int indexi = tabletti.rowAtPoint(evt.getPoint());
        
        
       
           
        int id = Integer.parseInt("" + tabletti.getValueAt(indexi, 0));
        
        if (id > 1) {
        String firstname = "" + tabletti.getValueAt(indexi, 1);
        String lastname = "" + tabletti.getValueAt(indexi, 2);
        String sposti = "" + tabletti.getValueAt(indexi, 3);
        String puhnum = "" + tabletti.getValueAt(indexi, 4);
        String muistiinpanot = "" + tabletti.getValueAt(indexi, 5);
        
        
        
        
       SingleCustomer singlecustomer = new SingleCustomer(Mainclass.firstpage, true);
       singlecustomer.setLabels(id, firstname, lastname, sposti, puhnum, muistiinpanot);
            try {
                singlecustomer.setTable();
            } catch (SQLException ex) {
                Logger.getLogger(CustomersDialog.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(CustomersDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
       singlecustomer.setVisible(true);
        }
         
        
        else {
            JOptionPane.showMessageDialog(rootPane, "Voit muokata tyhjää pöytää vain manuaalisesti, käyttäen tietokanta komentoja");
        }
         }
    }//GEN-LAST:event_tablettiMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String haku = JOptionPane.showInputDialog("Anna hakusana ");
      AccessToMysql mysql = new AccessToMysql();
      mysql.connectah();
       DefaultTableModel model = (DefaultTableModel) tabletti.getModel();
       model.setRowCount(0);
       
       haku = "'%" + haku + "%'";
      try {
          tablemodel = mysql.getcustomersbysearch(tablemodel, haku);
      } catch (SQLException ex) {
          Logger.getLogger(CustomersDialog.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ParseException ex) {
          Logger.getLogger(CustomersDialog.class.getName()).log(Level.SEVERE, null, ex);
      }
       tabletti.setModel(tablemodel);
        this.tabletti.setDefaultEditor(Object.class, null);
      try {
          mysql.closeConnect();
      } catch (SQLException ex) {
          Logger.getLogger(CustomersDialog.class.getName()).log(Level.SEVERE, null, ex);
      }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomersDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomersDialog dialog = new CustomersDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabletti;
    // End of variables declaration//GEN-END:variables
}
