
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miko ja Nastia
 */
public class falsePays extends javax.swing.JDialog {
           String col[] = {"Kuitti NRO", "Pöytä NRO","Maksutapa","PVM", "Klo", "Hinta", "Myynti ID"};     
           DefaultTableModel model = new DefaultTableModel(col, 0);
    /**
     * Creates new form falsePays
     */
    public falsePays(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void setTable() throws SQLException, ParseException {
        
      
       model.setRowCount(0);
         AccessToMysql mysql = new AccessToMysql();
          mysql.connectah();
          model = mysql.falsepays(model);
            tabletti.setModel(model);
            
            String yhteensastr = "" + mysql.getfalsemyynnit();
            
            yhteensa.setText(yhteensastr);
        mysql.closeConnect();
        
          this.tabletti.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabletti = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yhteensa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabletti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabletti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablettiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabletti);

        jLabel1.setText("Virheiden hallintatila");

        jLabel2.setText("Virheelliset myynnit yhteensä:");

        yhteensa.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(yhteensa)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yhteensa))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablettiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablettiMouseClicked
        if (evt.getClickCount() == 2) {
            
         int indexi = tabletti.rowAtPoint(evt.getPoint());
         
         String kuittistr = (String) tabletti.getValueAt(indexi, 0);
         String poytastr = (String) tabletti.getValueAt(indexi, 1);
         
         int kuittinro = Integer.parseInt(kuittistr);
         int poytanro = Integer.parseInt(poytastr);
         String maksutapa = (String) tabletti.getValueAt(indexi, 2);
         String pvm = (String) tabletti.getValueAt(indexi, 3);
         String kello = (String) tabletti.getValueAt(indexi, 4);
         String hinta = (String) tabletti.getValueAt(indexi, 5);
         String myyntiiidee = (String) tabletti.getValueAt(indexi, 6);
        falsepaysingle single = new falsepaysingle(Mainclass.firstpage, true);
        single.setLabels(1, poytanro, hinta, pvm, kello, maksutapa, kuittistr, myyntiiidee);
        single.setVisible(true);
      
    }
    }//GEN-LAST:event_tablettiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(falsePays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(falsePays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(falsePays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(falsePays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                falsePays dialog = new falsePays(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabletti;
    private javax.swing.JLabel yhteensa;
    // End of variables declaration//GEN-END:variables
}
